add Proposal data & Web-site framework
JSCIG/jscig.github.io pull request #1
Opened 2020-09-22 17:04 UTC by TechQuery

- **ECMAScript Proposal** crawler & data
- **PWA** framework based on [WebCell v2](https://web-cell.dev/)

2020-09-22 18:44 UTC, hax commented
棒。本次会议结束我review一下。

2020-09-23 11:10 UTC, septs commented on .github/workflows/main.yml
> +        uses: actions/setup-node@v1
https://github.com/actions/setup-node#v2-beta

2020-09-23 11:10 UTC, septs commented on .github/workflows/main.yml
> +          forceOrphan: true
```suggestion
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          force_orphan: true
```

2020-09-23 11:10 UTC, septs commented on README.md
> +cd ./JSCIG
```suggestion
git clone https://github.com/JSCIG/jscig.github.io
cd jscig.github.io
```

2020-09-23 11:10 UTC, septs commented on package.json
> +  "author": "shiy2008@gmail.com",
we may need official domain and email forward service.

e.q:
```
jscig.tech
jscig.io
```

for workgroup member:
e.q:
```
septs@jscig.tech
```

2020-09-23 11:10 UTC, septs commented on package.json
> +  "license": "AGPL-3.0",
```suggestion
  "license": "UNLICENSED",
```

I think it should be `UNLICENSED`.

see https://docs.npmjs.com/files/package.json#license

2020-09-23 11:10 UTC, septs commented on package.json
> +  "version": "1.0.0",
remove `"version"` field.
and add `"private": true`

https://docs.npmjs.com/files/package.json#private

2020-09-23 11:10 UTC, septs commented on package.json
> +  },
extract to file, `.lintstagedrc`.

2020-09-23 11:10 UTC, septs commented on package.json
> +  },
extract to file, `.prettierrc.json`.

2020-09-23 11:10 UTC, septs commented on package.json
> +  },
extract to file, `.postcss.config.js`.

2020-09-23 11:10 UTC, septs commented on source/data/crawler.js
> +//    (c)2020  @TechQuery
Why Copyright not is `JSCIG Workgroup`?

2020-09-23 11:10 UTC, septs commented on source/page/Main.tsx
> +          JSCIG 主要侧重于确定中国 JavaScript 开发者的需求、帮助 Ecma
```suggestion
          JSCIG 主要侧重于确定中国 JavaScript 开发者的需求、帮助 ECMA
```

2020-09-23 11:11 UTC, septs commented
![image](https://user-images.githubusercontent.com/3842474/94005221-8d11cb80-fdd0-11ea-860e-cab90d0f3b56.png)

hmmmmmmmm

2020-09-23 11:38 UTC, TechQuery commented on .github/workflows/main.yml
> +        uses: actions/setup-node@v1
这个测试版你用着稳定我就跟进

2020-09-23 11:38 UTC, TechQuery commented on .github/workflows/main.yml
> +          forceOrphan: true
看了一下文档，Personal Token 更普适一些

2020-09-23 11:39 UTC, TechQuery commented on README.md
> +cd ./JSCIG
目录名太长，我就改短了

2020-09-23 11:40 UTC, TechQuery commented on package.json
> +  "author": "shiy2008@gmail.com",
**域名**问题需要另开一个 issue 来讨论

2020-09-23 11:42 UTC, TechQuery commented on package.json
> +  "version": "1.0.0",
`version` 我通常来记录开发阶段，[官方文档](https://docs.npmjs.com/files/package.json#version)也说 `private` 项目中是可选的

2020-09-23 11:44 UTC, TechQuery commented on package.json
> +  },
`private` 项目本来 `package.json` 内容就不多，**总行不超过 100** 或**每项工具配置不太长**，我一般不单列配置文件，**让根目录清爽一些**

2020-09-23 11:47 UTC, TechQuery commented on source/data/crawler.js
> +//    (c)2020  @TechQuery
看很多公司的开源项目，**代码版权注释**一般是_个人+组织_，我加一个 @JSCIG 吧

2020-09-23 11:49 UTC, TechQuery commented on source/page/Main.tsx
> +          JSCIG 主要侧重于确定中国 JavaScript 开发者的需求、帮助 Ecma
贺老在 [B 站的某期视频](https://www.bilibili.com/video/BV1xT4y1L7ui)中好像讲过他们改成大驼峰了……

2020-09-23 11:54 UTC, TechQuery commented
@septs GitHub API 在不要求用户登录的情况下会[限制每小时请求数](https://developer.github.com/v3/#rate-limiting)

2020-09-23 11:55 UTC, septs commented on README.md
> +cd ./JSCIG
其实没有必要写怎么 clone。

2020-09-23 11:56 UTC, septs commented on .github/workflows/main.yml
> +          forceOrphan: true
personal token 会以你个人的生活发布。

github_token 是以 github-actions 的身份发布的

2020-09-23 11:57 UTC, septs commented on .github/workflows/main.yml
> +        uses: actions/setup-node@v1
@dimensiondev 广泛使用中。

2020-09-23 11:58 UTC, septs commented on package.json
> +  "version": "1.0.0",
对于 website 来说没有任何必要
相对于这个项目来说 private: true 是需要的

2020-09-23 11:58 UTC, septs commented on source/data/crawler.js
> +//    (c)2020  @TechQuery
还有根目录下的 LICENSE 文件。。。

2020-09-23 11:59 UTC, septs commented
> @septs GitHub API 在不要求用户登录的情况下会[限制每小时请求数](https://developer.github.com/v3/#rate-limiting)

可以考虑修改成，通过 gh-actions 每天运行一次更新数据。

2020-09-23 12:17 UTC, TechQuery commented
@septs 那得再写个 Node.js 脚本更新 JSON，但一般用户不会 _在未登录的状态下经常调用 GitHub API_ 吧？

2020-09-23 12:19 UTC, TechQuery commented on README.md
> +cd ./JSCIG
新人带多了就习惯 _奶妈教程_

2020-09-23 12:21 UTC, TechQuery commented on source/data/crawler.js
> +//    (c)2020  @TechQuery
`UNLICENSED` 还哪来的 License 文件？

2020-09-23 15:53 UTC, septs commented
> @septs 那得再写个 Node.js 脚本更新 JSON，但一般用户不会 _在未登录的状态下经常调用 GitHub API_ 吧？

其实不需要，你在每次的编译过程中拉数据就好了

https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onschedule

2020-09-23 15:54 UTC, septs commented on package.json
> +  "author": "shiy2008@gmail.com",
建议留空。

2020-09-23 17:16 UTC, TechQuery commented
页面上呈现的数据整合自[手工整理的基础数据](https://github.com/TechQuery/JSCIG/tree/master/source/data)和 GitHub API：

https://github.com/TechQuery/JSCIG/blob/7d78f457b071e90929e60d27045d630e27efe83c/source/model/Proposal.ts#L67-L82

2020-09-23 23:51 UTC, septs commented on package.json
> +  },
```suggestion
  "repository": "https://github.com/JSCIG/jscig.github.io",
  "bugs": "https://github.com/JSCIG/jscig.github.io/issues",
```

2020-09-23 23:53 UTC, septs requested changes

2020-09-23 23:53 UTC, septs commented on package.json
> +  },
```suggestion
  "repository": "https://github.com/JSCIG/jscig.github.io",
  "bugs": "https://github.com/JSCIG/jscig.github.io/issues",
```

2020-09-23 23:53 UTC, septs commented on source/page/Main.tsx
> +            JSCIG 主要侧重于确定中国 JavaScript 开发者的需求、帮助 Ecma
```suggestion
            JSCIG 主要侧重于确定中国 JavaScript 开发者的需求、帮助 ECMA
```

2020-09-24 01:00 UTC, septs commented
https://jscig.github.io/dataset/proposals.json

UTC 时间 0 点更新

2020-09-24 11:58 UTC, TechQuery commented on package.json
> +  },
能这样写吗？我只是 `npm init -y` 生成的

2020-09-24 12:00 UTC, TechQuery commented on source/page/Main.tsx
> +            JSCIG 主要侧重于确定中国 JavaScript 开发者的需求、帮助 Ecma
我前面说过了 https://github.com/JSCIG/jscig.github.io/pull/1#discussion_r493494298 ，又去官网确认了 https://www.ecma-international.org/

2020-09-24 12:31 UTC, septs commented
@TechQuery pushed_at 可以作为最后更新时间（建议非 Stage 4 且超过 3 个月的可标记成不活跃

2020-09-24 12:34 UTC, TechQuery commented
> @TechQuery pushed_at 可以作为最后更新时间（建议非 Stage 4 且超过 3 个月没有 push 的可标记成不活跃

“最近更新”是指“最近一次更新进度的会议”，并有对应的会议链接；“不活跃”还是以官方标记为准吧

2020-09-24 12:34 UTC, septs approved these changes

2020-09-24 13:50 UTC, septs requested changes

2020-09-24 13:50 UTC, septs commented on source/page/Proposal.tsx
> +            活跃提案共计 <strong>{data.length}</strong> 个
请筛选掉处于 Stage 4 和 inactive 的。

2020-09-24 16:28 UTC, septs requested changes

2020-09-24 16:28 UTC, septs commented on source/page/Main.tsx
> +          {list.map(({ html_url, login }) => (
https://api.github.com/orgs/JSCIG/members

2020-09-24 17:23 UTC, TechQuery commented on source/page/Main.tsx
> +          {list.map(({ html_url, login }) => (
咋了？就是用的这个 API

2020-09-24 17:30 UTC, septs commented on source/page/Main.tsx
> +          {list.map(({ html_url, login }) => (
OK

2020-09-25 03:35 UTC, septs requested changes
TypeError: Cannot read property 'includes' of undefined

2020-09-25 03:35 UTC, septs commented on source/page/Proposal.tsx
> +        ? list.filter(({ authors }) => authors.includes(author))
```suggestion
        ? list.filter(({ authors }) => authors?.includes(author))
```

2020-09-25 03:35 UTC, septs commented on source/page/Proposal.tsx
> +        ? list.filter(({ champions }) => champions.includes(champion))
```suggestion
        ? list.filter(({ champions }) => champions?.includes(champion))
```

2020-09-25 05:06 UTC, septs commented
根据 tags 区分下 ECMA-262 和 ECMA-402

2020-09-25 06:08 UTC, septs commented
```
  {
    "stage": 1,
    "name": "Change Number.parseInt/parseFloat to not coerce null/undefined/NaN (repo link TBD)",
    "champions": [
      "Brendan Eich"
    ]
  },
```

https://github.com/JSCIG/dataset/blob/gh-pages/proposals.json#L2437-L2443

2020-09-25 07:38 UTC, septs requested changes

2020-09-25 07:38 UTC, septs commented on source/model/Proposal.ts
> +export interface Proposal {
更新下数据结构

2020-09-25 10:33 UTC, septs commented
![image](https://user-images.githubusercontent.com/3842474/94257238-90868d80-ff5d-11ea-89ea-2b3f62cca1c7.png)

inactive 移动到了 tags 里面

2020-09-25 10:35 UTC, septs commented
作者 和 责编 完全相同的时候可以隐藏 责编

2020-09-25 10:39 UTC, TechQuery commented
> ![image](https://user-images.githubusercontent.com/3842474/94257238-90868d80-ff5d-11ea-89ea-2b3f62cca1c7.png)
> 
> inactive 移动到了 tags 里面

`-1` 很符合 JS API 返回值的习惯，挺好的；放在 `tags` 里索引位置不固定，也不方便我映射：
https://github.com/TechQuery/JSCIG/blob/39d2e01140a56d9e1d128f2e5c112cd598fdfcd0/source/page/Proposal.tsx#L22-L29

2020-09-25 10:42 UTC, septs requested changes

2020-09-25 10:42 UTC, septs commented on source/model/Proposal.ts
> +    );
```suggestion
    const finished = proposals.filter((proposal) => proposal.tags.include('finished'))
    const processing = proposals.filter((proposal) => proposal.tags.include('stage'))
```

2020-09-25 10:45 UTC, septs commented
@TechQuery 主要问题是 Stage 的定义不包括 inactive
所以放 tags 是合理的（ -1 会使得一些人感到迷惑

2020-09-25 10:45 UTC, TechQuery commented
> 作者 和 责编 完全相同的时候可以隐藏 责编

不同列的**筛选字段**不同，某一栏没有就筛下不了某一字段，合并单元格就等于筛选满足两个字段的行，范围太小：
https://github.com/TechQuery/JSCIG/blob/39d2e01140a56d9e1d128f2e5c112cd598fdfcd0/source/page/Proposal.tsx#L134-L158

2020-09-25 10:47 UTC, septs commented
我指的隐藏 责编 是对于 `TC39 既成提案` 来说的

对于表格，我建议修改下样式使用 `table-layout: fixed` 手动调节出合适列宽
https://developer.mozilla.org/en-US/docs/Web/CSS/table-layout

2020-09-25 10:47 UTC, TechQuery commented on source/model/Proposal.ts
> +    );
`.reduce()` 只需遍历一趟，比较快

2020-09-25 10:49 UTC, TechQuery commented
> Stage 的定义不包括 inactive

官方只定义了 0 ~ 4，那 `-1` 表示“冷宫”也挺合理的

2020-09-25 10:49 UTC, septs commented on source/page/Main.tsx
> +                  ES {year}
![image](https://user-images.githubusercontent.com/3842474/94258703-d3496500-ff5f-11ea-97f0-724232365c41.png)

https://github.com/tc39/proposal-promise-any

显然这是错误的假设

2020-09-25 10:53 UTC, TechQuery commented
> 我指的隐藏 责编 是对于 `TC39 既成提案` 来说的
> 
> 对于表格，我建议修改下样式使用 `table-layout: fixed` 手动调节出合适的列宽
> https://developer.mozilla.org/en-US/docs/Web/CSS/table-layout

**既成提案**后面也可能做个**筛选链接**指向**未成提案**。

每列都设置宽度？筛选后某些列很可能变短，**自适应宽度**挺好的。

2020-09-25 10:54 UTC, TechQuery commented on source/page/Main.tsx
> +                  ES {year}
不严谨，你有解决方案吗？

2020-09-25 10:58 UTC, septs commented
那可以考虑
```css
table a {
    white-space: nowrap;
}
```

2020-09-25 10:58 UTC, TechQuery commented
> 根据 tags 区分下 ECMA-262 和 ECMA-402 （现在可以用了，archived 移动到 tags 里面了

其实这里也应该改成形如 `"standard": 262` 的字段，我现在假定它在 `tags` 第一个，严谨的还得 `tags.find(tag => tag.startWiths('ECMA-'))`，性能又差……

2020-09-25 11:00 UTC, septs commented
> > 根据 tags 区分下 ECMA-262 和 ECMA-402 （现在可以用了，archived 移动到 tags 里面了
> 
> 其实这里也应该改成形如 `"standard": 262` 的字段，我现在假定它在 `tags` 第一个，严谨的还得 `tags.find(tag => tag.startWiths('ECMA-'))`，性能又差……

我的 design usage 是通过 filter tags 来分组
再做后继处理

2020-09-25 11:07 UTC, septs commented on source/page/Main.tsx
> +                  ES {year}
人工额外维护一份 errata

2020-09-25 11:08 UTC, TechQuery commented
> > > 根据 tags 区分下 ECMA-262 和 ECMA-402 （现在可以用了，archived 移动到 tags 里面了
> > 
> > 
> > 其实这里也应该改成形如 `"standard": 262` 的字段，我现在假定它在 `tags` 第一个，严谨的还得 `tags.find(tag => tag.startWiths('ECMA-'))`，性能又差……
> 
> 我的 design usage 是通过 filter tags 来分组
> 再做后继处理

但 `proposals` 页需要整体 `.filter()`，事先分了数组，后面又要 `.concat()`……

2020-09-25 11:08 UTC, septs commented on source/page/Main.tsx
> +            <dd>{authors.join(', ')}</dd>
https://mdn.io/Intl.ListFormat

2020-09-25 11:09 UTC, septs commented
> 后面又要 `.concat()`……

在这种地方担忧性能。。。。

2020-09-25 12:04 UTC, TechQuery commented on source/page/Main.tsx
> +            <dd>{authors.join(', ')}</dd>
![image](https://user-images.githubusercontent.com/19969570/94264826-0690f180-ff6a-11ea-887d-c99b23875f77.png)

`Intl.ListFormat()` 不在**中英文之间加空格**简直不能忍，我要推 [ZhLint](https://github.com/Jinjiang/zhlint) 进**国际化标准**

2020-09-25 12:05 UTC, TechQuery commented on source/page/Main.tsx
> +            <dd>{authors.join(', ')}</dd>
[polyfill 没全局类型定义](https://github.com/wessberg/intl-list-format/issues/2)也很难受……

2020-09-25 12:58 UTC, septs commented
dataset 更新好了

2020-09-25 15:42 UTC, septs commented on source/page/Main.tsx
> +                  ES {year}
用 edition 字段

2020-09-25 15:51 UTC, TechQuery commented on package.json
> +  "author": "shiy2008@gmail.com",
作者目前是我，后面有其它贡献者、组织域名了，再改

2020-09-25 23:20 UTC, septs requested changes

2020-09-25 23:20 UTC, septs commented on source/page/Proposal.tsx
> +          onClick={() => (proposal.sortKey = 'updated_at')}
应该用 pushed_at

2020-09-25 23:20 UTC, septs commented on source/page/Proposal.tsx
> +          onClick={() => (proposal.sortKey = 'published_at')}
这个是 created_at 的时间不能当作定案时间
只能视作提出的时间

2020-09-25 23:21 UTC, septs commented on source/page/Proposal.tsx
> +          onClick={() => (proposal.sortKey = 'updated_at')}
starred 会触发 updated_at 的更新

2020-09-25 23:21 UTC, septs commented on source/page/Proposal.tsx
> +          onClick={() => (proposal.sortKey = 'updated_at')}
看来我应该吧 updated_at 去掉

2020-09-25 23:22 UTC, septs commented on source/page/Proposal.tsx
> +          onClick={() => (proposal.sortKey = 'updated_at')}
去掉了

2020-09-26 02:17 UTC, septs commented on .github/workflows/main.yml
> +          npm install
```suggestion
          npm ci
```

2020-09-26 02:35 UTC, septs commented on source/page/Proposal.tsx
> +          onClick={() => (proposal.sortKey = 'updated_at')}
meeting_at 解析出来了，可以按照 meeting_at 排序。

2020-09-26 08:15 UTC, TechQuery commented on .github/workflows/main.yml
> +          npm install
我本地用 Yarn 装的，只有 `yarn.lock`，没法用 `npm ci` 吧？

2020-09-26 08:21 UTC, TechQuery commented on source/page/Proposal.tsx
> +          onClick={() => (proposal.sortKey = 'published_at')}
这一列我删了，定案看首页的“既成提案”吧

2020-09-26 10:02 UTC, septs commented on source/page/Main.tsx
> +              {standard === '262' && edition <= thisYear ? (
2020 年的规范是 2021 年发布的，因此是 
```suggestion
              {standard === '262' && edition < thisYear ? (
```

2020-09-26 10:03 UTC, septs commented on source/page/Proposal.tsx
> +    const updated = formatDate(meeting_at || pushed_at, 'YYYY 年 M 月');
```suggestion
    const updated = formatDate(meeting_at ?? pushed_at ?? NaN, 'YYYY 年 M 月');
```

```
> new Date(NaN)
< Invalid Date
```

2020-09-26 10:09 UTC, septs commented on .github/workflows/main.yml
> +          npm install
```bash
yarn install --frozen-lockfile
```

see https://classic.yarnpkg.com/en/docs/cli/install/#toc-yarn-install

2020-09-26 10:23 UTC, septs commented on source/model/Proposal.ts
> +        tags,
```suggestion
        tags,
```

可以吧 tags 转换成一个 `Record<string, true>`

然后就这么用

```
record.tags['ECMA-262'] && record.edition < year
```

```
record.tags['co-champion'] && record.edition < year
```

2020-09-26 11:07 UTC, TechQuery commented on .github/workflows/main.yml
> +          npm install
这个命令会生成 `package-lock.json` 吗？

2020-09-26 11:08 UTC, septs commented on .github/workflows/main.yml
> +          npm install
使用 `yarn.lock` 安装

2020-09-26 11:09 UTC, TechQuery commented on source/page/Main.tsx
> +              {standard === '262' && edition <= thisYear ? (
![image](https://user-images.githubusercontent.com/19969570/94339326-c6924300-002b-11eb-897a-d17701e16644.png)
你这么改的话，这个有效链接也显示不出来了

2020-09-26 11:11 UTC, septs commented on source/page/Main.tsx
> +              {standard === '262' && edition <= thisYear ? (
那么应该是在今年以前的有链接行为
在此之后的没有

2020-09-26 11:12 UTC, TechQuery commented on source/model/Proposal.ts
> +        tags,
那我不但要自己转数据结构，还要定义两套 `interface`……

2020-09-26 11:19 UTC, TechQuery commented on source/page/Proposal.tsx
> +    const updated = formatDate(meeting_at || pushed_at, 'YYYY 年 M 月');
这么改会让代码挂掉 https://github.com/EasyWebApp/web-utility/blob/b8c81ce/source/date.ts#L51

2020-09-26 11:21 UTC, septs commented on source/page/Proposal.tsx
> +    const updated = formatDate(meeting_at || pushed_at, 'YYYY 年 M 月');
那是你没处理这个 edge case。。。。

2020-09-26 11:21 UTC, septs commented on source/page/Proposal.tsx
> +    const updated = formatDate(meeting_at || pushed_at, 'YYYY 年 M 月');
不过这不算什么很特殊的 edge case

2020-09-26 11:21 UTC, TechQuery commented on source/page/Main.tsx
> +              {standard === '262' && edition <= thisYear ? (
所以 `<=` 有何问题？

2020-09-26 11:22 UTC, TechQuery commented on .github/workflows/main.yml
> +          npm install
官方文档说 `npm ci` 需要 `package-lock.json`……

2020-09-26 11:22 UTC, septs commented on source/page/Proposal.tsx
> +    const updated = formatDate(meeting_at || pushed_at, 'YYYY 年 M 月');
```js
Number.isNaN(new Date(NaN).getTime()) === true
```

2020-09-26 11:23 UTC, septs commented on source/page/Main.tsx
> +              {standard === '262' && edition <= thisYear ? (
好像没问题。。

2020-09-26 11:46 UTC, septs commented on .github/workflows/main.yml
> +          npm install
我的意思你吧 `yarn.lock` 上传，使用
```
yarn install --frozen-lockfile
```
安装，此时使用的是 `yarn.lock`

2020-09-26 12:23 UTC, TechQuery commented on source/page/Proposal.tsx
> +    const updated = formatDate(meeting_at || pushed_at, 'YYYY 年 M 月');
我后面看看怎么改上游库吧

2020-09-26 12:26 UTC, TechQuery commented on .github/workflows/main.yml
> +          npm install
前端项目我一般不上传 lock 文件，我有 Git history 洁癖

2020-09-28 07:42 UTC, septs commented
@TechQuery 新增 `spec` 字段指向规范的 URL

2020-09-28 07:49 UTC, septs commented on source/data/members-china.json
> +    "name": "Suji Tech",
Sujitech

2020-09-28 07:50 UTC, septs commented on source/page/Main.tsx
> +                href={`https://www.ecma-international.org/publications/standards/Ecma-${standard}.htm`}
```suggestion
                href={`https://tc39.es/ecma${standard}/`}
```

https://tc39.es/ecma262/
https://tc39.es/ecma402/

2020-09-28 07:52 UTC, septs commented on source/page/index.tsx
> +            'https://www.ecma-international.org/publications/standards/Ecma-262.htm'
```suggestion
            'https://tc39.es/ecma262/'
```

2020-09-28 07:52 UTC, septs commented on source/page/index.tsx
> +            'https://www.ecma-international.org/publications/standards/Ecma-402.htm'
```suggestion
            'https://tc39.es/ecma402/'
```

2020-09-28 08:33 UTC, septs commented
https://github.com/tc39/tc39.github.io/pull/211 ummmmmm

2020-09-30 06:48 UTC, septs requested changes
格式化下全部文件，`yarn prettier -w .`

2020-09-30 10:39 UTC, TechQuery commented
> 格式化下全部文件，`yarn prettier -w .`

https://github.com/TechQuery/JSCIG/blob/9ab517fbd20b77058bac666ef6a68cb2bc3eec85/package.json#L46-L50

2020-09-30 10:41 UTC, septs commented
@TechQuery 你从我的 changes 里面直接并入的，显然不会经过 formatter
当然要求你全都格式化一下

2020-09-30 10:42 UTC, merged